services:
  - type: web
    name: visiocampus-mediasoup
    env: node
    plan: free
    branch: master
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
